# render.yaml - Blueprint for deploying Crop Sathi on Render
#
# This file defines the services and infrastructure needed to run the application.
# Render can automatically build and deploy your app using this file.
# For more details, see: https://render.com/docs/blueprint-spec

services:
  # 1. A PostgreSQL database for our application
  - type: psql
    name: cropsathi-db
    plan: free # Use the free plan for demonstration purposes
    # The following properties are set automatically by Render:
    # - databaseName: cropsathi_db
    # - user: cropsathi_db_user

  # 2. The FastAPI web service
  - type: web
    name: cropsathi-app
    plan: free # Use the free plan for demonstration purposes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cropsathi-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11 # Specify a recent Python version